<a href="https://colab.research.google.com/github/Ramaraju-77/collab/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform arithmetic operations on NumPy arrays.


In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition of array:",a+b)
print("subtraction of array:",a-b)
print("multiplication of array:",a*b)
print("division of array:",a/b)

addition of array: [5 7 9]
subtraction of array: [-3 -3 -3]
multiplication of array: [ 4 10 18]
division of array: [0.25 0.4  0.5 ]


 Write a script to compute the mean and standard deviation of a NumPy array.


In [6]:
a=np.array([1,2,3,4,5])
print("mean of array: ",np.mean(a))
print("standard deviation of array: ",np.std(a))

mean of array:  3.0
standard deviation of array:  1.4142135623730951


Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [4]:
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


 Reshape the array into a 2x4 matrix.


In [5]:
matrix=a.reshape(2,4)
print(matrix)

[[10 15 20 25]
 [30 35 40 45]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_matrix=a[1:,:2]
print(sub_matrix)
a[a>4]=0
print(a)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition of array:",a+b)
print("multiplication of array:",a*b)
print("division of array:",a/b)

addition of array: [5 7 9]
multiplication of array: [ 4 10 18]
division of array: [0.25 0.4  0.5 ]


Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.


In [11]:
a=np.random.rand(4,4)
print("mean of each column: ",np.mean(a,axis=0))
print("maximum value of the entire array: ",np.max(a))

mean of each column:  [0.6328537  0.64817439 0.59440679 0.57183827]
maximum value of the entire array:  0.9926159785551041


Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2

In [12]:
a= np.array([1, 2, 3, 4])
result = (a+ 10) * 2
print(result)

[22 24 26 28]


Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [17]:
a=np.random.randint(1,101,size=(3,4,5))
print(a)
print("second layer",a[1])
print("first two rows and last three coloums",a[:,:2,-3:])
a[a%3==0]=-1
print(a)


[[[96 15 19 98 56]
  [13 81  7 60 23]
  [33 99 46 55 67]
  [86 90 98 47 89]]

 [[38 69 16 38 89]
  [99 88 46 27 57]
  [46 19 49 55 73]
  [90 43 84 96 29]]

 [[71 14 32 26 79]
  [70 83 22 32 51]
  [12 43 87 91 22]
  [32 11 89 54 11]]]
second layer [[38 69 16 38 89]
 [99 88 46 27 57]
 [46 19 49 55 73]
 [90 43 84 96 29]]
first two rows and last three coloums [[[19 98 56]
  [ 7 60 23]]

 [[16 38 89]
  [46 27 57]]

 [[32 26 79]
  [22 32 51]]]
[[[-1 -1 19 98 56]
  [13 -1  7 -1 23]
  [-1 -1 46 55 67]
  [86 -1 98 47 89]]

 [[38 -1 16 38 89]
  [-1 88 46 -1 -1]
  [46 19 49 55 73]
  [-1 43 -1 -1 29]]

 [[71 14 32 26 79]
  [70 83 22 32 -1]
  [-1 43 -1 91 22]
  [32 11 89 -1 11]]]


Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [22]:
a=np.random.randint(1,21,size=(3,3))
print(a)
print("row-wise normalisation:",a-a.mean(axis=1,keepdims=True))
print("new array:",np.square(a))
print("top 3 maximum values:",np.argsort(a.flatten())[-3:])



[[17 11  4]
 [16 13 18]
 [11  1 14]]
row-wise normalisation: [[ 6.33333333  0.33333333 -6.66666667]
 [ 0.33333333 -2.66666667  2.33333333]
 [ 2.33333333 -7.66666667  5.33333333]]
new array: [[289 121  16]
 [256 169 324]
 [121   1 196]]
top 3 maximum values: [3 0 5]
